name : Our Wedding
brand : Bryan & Janice
description : This is the webpage for Bryan and Janice's wedding
keyword :
url : http://bryanjanice.github.io
email : bryanjanice@gmail.com
twitter : ytbryan
github : ytbryan
author : Bryan & Janice
analytics :
year : 2015
markdown : kramdown
